sudo: required
dist: trusty
language: cpp

branches:
  only:
    - master
    - master_coverity_scan
    - /^stable-.*$/

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - wget --no-check-certificate http://www.cmake.org/files/v3.1/cmake-3.1.2-Linux-x86_64.sh
  - sudo bash ./cmake-3.1.2-Linux-x86_64.sh --prefix=/usr/local/ --skip-license --exclude-subdir
  - sudo add-apt-repository ppa:beineri/opt-qt57-trusty --yes
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - gpg --keyserver pgpkeys.mit.edu --recv-key 15CF4D18AF4F7421
  - gpg -a --export 15CF4D18AF4F7421 | sudo apt-key add -
  - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main' --yes
  - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main' --yes
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa --yes
  - sudo apt-get update
  - if [ "$CXX" = "g++" ]; then sudo apt-get install --yes --force-yes g++-4.9; else sudo apt-get install --yes --force-yes clang-3.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; else export CXX="clang++-3.9" CC="clang-3.9"; fi
  - sudo apt-get install --yes --force-yes cmake libclucene-dev qt57base qt57declarative qt57svg qt57tools qt57webengine qt57xmlpatterns
  - source /opt/qt57/bin/qt57-env.sh
  - svn checkout --non-interactive http://crosswire.org/svn/sword/trunk sword-trunk
  - cd sword-trunk
  - mkdir b
  - cd b
  - cmake ..
  - make
  - sudo make install
  - cd ../..

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then mkdir b && cd b && /usr/local/bin/cmake .. && make && sudo make install; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VjsU8+6Sca7TXbR5zQstHw6eb4Dv0ZifqE29DRT+n64VKxAWFaWazJ4VJNlHvd8ChiJRfFcXVVXfNgNMAHE/JJHt1GgSPwIqSEE2mQh+7tqfSeBV/5yBkF7Fs4QIOrWjdEhEHTt0+wc6wtoVghEHvWlk3Lymb4x0UQDZtz/a4cI="

addons:
  coverity_scan:
    project:
      name: "bibletime/bibletime"
      description: "BibleTime build submitted via Travis CI"
    notification_email: bibletime-coverity@heh.ee
    build_command_prepend: "mkdir b && cd b && /usr/local/bin/cmake .."
    build_command: "make"
    branch_pattern: .*_coverity_scan

notifications:
  irc: "chat.freenode.net#bibletime"
